### ISSUE TITLE
Rewrite css into adaptive layout

### ISSUE THREAD

**Issue by gebriallairbeg** [SuperLalka/Training_project-2#2]
Right now page may be visible correct  only on > 800 px wide screens.
But it should use relative layout according to device that opened this page

https://github.com/SuperLalka/Training_project-2/blob/422a03a3c242283fbf7bcaad1e5e5e3dbf20ba55/css/style.css#L8

**Comment by SuperLalka** [comment]
Added 3 state for screen device

**Comment by gebriallairbeg** [comment]
ok, basically works well, but bug fount https://github.com/SuperLalka/Training_project-2/issues/4
