### ISSUE TITLE
Move all used images into one directory

### ISSUE THREAD

**Issue by gebriallairbeg** [SuperLalka/Training_project-2#3]
Right now some images placed in design/ directory, and some into css/images

Its bad practice, to store sources in different places, so you should move all images into one directory (for example, name it "img") and place this directory into root for project, so you will get project like

```
/css/
/img/
index.html
```

 don't forget to update css/html to use new relative paths, because use will change it, and images may disappear from page)

**Comment by SuperLalka** [comment]
Сompleted

**Comment by gebriallairbeg** [comment]
ok, done
